package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"strings"
	"testing"
)

func requestJSON(
	t *testing.T,
	requestID string,
	relativePath string,
	content []byte,
) []byte {
	t.Helper()

	request := classifyRequest{
		SchemaVersion: schemaVersion,
		RequestID:     requestID,
		RelativePath:  relativePath,
		ContentBase64: base64.StdEncoding.EncodeToString(content),
	}

	encoded, err := json.Marshal(request)
	if err != nil {
		t.Fatalf("encode request: %v", err)
	}

	return encoded
}

func decodeResponse(
	t *testing.T,
	data []byte,
) classifyResponse {
	t.Helper()

	var response classifyResponse
	if err := json.Unmarshal(data, &response); err != nil {
		t.Fatalf("decode response: %v", err)
	}

	return response
}

func TestClassifyPython(t *testing.T) {
	request, content, errorCode := decodeRequest(
		requestJSON(
			t,
			"request-1",
			"src/app.py",
			[]byte("def main():\n    print('hello')\n"),
		),
	)

	if errorCode != "" {
		t.Fatalf("unexpected error code: %s", errorCode)
	}

	response := classify(request, content)

	if !response.OK {
		t.Fatal("expected successful classification")
	}
	if response.Language != "Python" {
		t.Fatalf(
			"expected Python, got %q",
			response.Language,
		)
	}
	if !contains(response.CandidateLanguages, "Python") {
		t.Fatalf(
			"Python missing from candidates: %#v",
			response.CandidateLanguages,
		)
	}
	if response.IsBinary {
		t.Fatal("Python source must not be binary")
	}
}

func TestClassifyBinary(t *testing.T) {
	request, content, errorCode := decodeRequest(
		requestJSON(
			t,
			"request-2",
			"assets/blob.bin",
			[]byte{0, 1, 2, 3},
		),
	)

	if errorCode != "" {
		t.Fatalf("unexpected error code: %s", errorCode)
	}

	response := classify(request, content)

	if !response.IsBinary {
		t.Fatal("expected binary classification")
	}
	if response.Language != "" {
		t.Fatalf(
			"binary file received language %q",
			response.Language,
		)
	}
	if len(response.CandidateLanguages) != 0 {
		t.Fatalf(
			"binary file received candidates: %#v",
			response.CandidateLanguages,
		)
	}
}

func TestFileFlags(t *testing.T) {
	cases := []struct {
		name         string
		relativePath string
		content      []byte
		assertion    func(classifyResponse) bool
	}{
		{
			name:         "vendor",
			relativePath: "vendor/example/lib.go",
			content:      []byte("package example\n"),
			assertion: func(response classifyResponse) bool {
				return response.IsVendor
			},
		},
		{
			name:         "generated",
			relativePath: "src/generated.go",
			content: []byte(
				"// Code generated by SecureScan. DO NOT EDIT.\n" +
					"package generated\n",
			),
			assertion: func(response classifyResponse) bool {
				return response.IsGenerated
			},
		},
		{
			name:         "test",
			relativePath: "src/app_test.go",
			content:      []byte("package app\n"),
			assertion: func(response classifyResponse) bool {
				return response.IsTest
			},
		},
		{
			name:         "documentation",
			relativePath: "README.md",
			content:      []byte("# Project\n"),
			assertion: func(response classifyResponse) bool {
				return response.IsDocumentation
			},
		},
		{
			name:         "configuration",
			relativePath: "config.yaml",
			content:      []byte("enabled: true\n"),
			assertion: func(response classifyResponse) bool {
				return response.IsConfiguration
			},
		},
		{
			name:         "dotfile",
			relativePath: ".env",
			content:      []byte("DEMO=value\n"),
			assertion: func(response classifyResponse) bool {
				return response.IsDotFile
			},
		},
	}

	for index, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			request, content, errorCode := decodeRequest(
				requestJSON(
					t,
					"flag-request",
					testCase.relativePath,
					testCase.content,
				),
			)

			if errorCode != "" {
				t.Fatalf(
					"case %d produced %s",
					index,
					errorCode,
				)
			}

			response := classify(request, content)

			if !testCase.assertion(response) {
				t.Fatalf(
					"expected flag for %s: %#v",
					testCase.name,
					response,
				)
			}
		})
	}
}

func TestRejectUnknownJSONField(t *testing.T) {
	line := []byte(
		`{"schema_version":"1.0.0",` +
			`"request_id":"request-1",` +
			`"relative_path":"src/app.py",` +
			`"content_base64":"",` +
			`"unexpected":true}`,
	)

	response := processLine(line)

	if response.OK {
		t.Fatal("unknown field must be rejected")
	}
	if response.ErrorCode != "INVALID_JSON" {
		t.Fatalf(
			"unexpected code: %s",
			response.ErrorCode,
		)
	}
}

func TestRejectPathEscape(t *testing.T) {
	line := requestJSON(
		t,
		"request-1",
		"../escape.py",
		[]byte("print('escape')\n"),
	)

	response := processLine(line)

	if response.OK {
		t.Fatal("path escape must be rejected")
	}
	if response.ErrorCode != "INVALID_RELATIVE_PATH" {
		t.Fatalf(
			"unexpected code: %s",
			response.ErrorCode,
		)
	}
}

func TestRejectInvalidBase64(t *testing.T) {
	line := []byte(
		`{"schema_version":"1.0.0",` +
			`"request_id":"request-1",` +
			`"relative_path":"src/app.py",` +
			`"content_base64":"%%%INVALID%%%"}`,
	)

	response := processLine(line)

	if response.OK {
		t.Fatal("invalid base64 must be rejected")
	}
	if response.ErrorCode != "INVALID_CONTENT" {
		t.Fatalf(
			"unexpected code: %s",
			response.ErrorCode,
		)
	}
}

func TestRejectOversizedContent(t *testing.T) {
	content := bytes.Repeat(
		[]byte("a"),
		maxDecodedContentBytes+1,
	)

	line := requestJSON(
		t,
		"request-1",
		"src/large.py",
		content,
	)

	response := processLine(line)

	if response.OK {
		t.Fatal("oversized content must be rejected")
	}
	if response.ErrorCode != "CONTENT_LIMIT_EXCEEDED" {
		t.Fatalf(
			"unexpected code: %s",
			response.ErrorCode,
		)
	}
}

func TestRunMultipleRequests(t *testing.T) {
	first := requestJSON(
		t,
		"request-1",
		"src/app.py",
		[]byte("print('hello')\n"),
	)
	second := requestJSON(
		t,
		"request-2",
		"assets/blob.bin",
		[]byte{0, 1, 2},
	)

	input := bytes.NewBuffer(nil)
	input.Write(first)
	input.WriteByte('\n')
	input.Write(second)
	input.WriteByte('\n')

	output := bytes.NewBuffer(nil)
	errorOutput := bytes.NewBuffer(nil)

	exitCode := run(
		input,
		output,
		errorOutput,
	)

	if exitCode != 0 {
		t.Fatalf(
			"unexpected exit code %d: %s",
			exitCode,
			errorOutput.String(),
		)
	}

	lines := strings.Split(
		strings.TrimSpace(output.String()),
		"\n",
	)

	if len(lines) != 2 {
		t.Fatalf(
			"expected two responses, got %d",
			len(lines),
		)
	}

	firstResponse := decodeResponse(
		t,
		[]byte(lines[0]),
	)
	secondResponse := decodeResponse(
		t,
		[]byte(lines[1]),
	)

	if firstResponse.RequestID != "request-1" ||
		firstResponse.Language != "Python" {
		t.Fatalf(
			"unexpected first response: %#v",
			firstResponse,
		)
	}

	if secondResponse.RequestID != "request-2" ||
		!secondResponse.IsBinary {
		t.Fatalf(
			"unexpected second response: %#v",
			secondResponse,
		)
	}
}
